<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.00">
  <DataList Id="186a11f3-40cf-4c92-80c7-bae96dbc2a34" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/1379f202-7cbe-47e3-871c-80ca2ec7de90" PlcIdentifier="6aff7cb6-d8e0-48c1-a326-d8cad274e635" TargetAttributes="PlcNext" UICulture="de-DE">
    <Datum Uuid="b91054d5-6d7e-4f44-bb48-5d7d3cf4a598">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1cc2a583-1a3f-49a7-8660-ffbd07a0d809" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_PLC_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Überlagerte Steuerung in Status RUN</Comment>
        <DisplayName>PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_PLC_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cc97169a-51ac-4974-9133-faf5af9aaa63">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="979e3cd2-01ce-4f09-b8e6-e12bbcbfc5eb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Verbindung zu Profinet Controller</Comment>
        <DisplayName>PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="dcfc2182-9a92-45e8-b3bd-7c0d73a60c2d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e3bd4e28-6e1f-4de5-b757-6e9257a4a478" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>IOP-Status der überlagerten Steuerung </Comment>
        <DisplayName>PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="18f1b8ce-b876-4a42-8d8a-ede41bc0ae0c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2cf6ec30-de89-4ab6-83d2-34091d8e9671" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>IOC-Status der überlagerten Steuerung </Comment>
        <DisplayName>PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="45ca5bb5-e2e9-44f9-a0e2-2af4f25d8609">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="370f5ab5-3059-473f-9465-d2139d9a652c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_DATA_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Prozessdatenlänge</Comment>
        <DisplayName>PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_DATA_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="020bf624-745e-42af-841d-b9bd786c616f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="84ab98da-f053-4461-8402-13d67e7419fd" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Ausgangs-Prozessdaten</Comment>
        <DisplayName>PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8d532e75-8dac-46e4-9a67-d4070d96b144">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ccbeae74-d079-4b90-a2f5-a0c79f36f06e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_S1_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Eingangs-Prozessdaten</Comment>
        <DisplayName>PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_S1_INPUTS</Label>
        <Access>I</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9a9be554-9506-48f8-9200-8019b53e7804">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6c5281e9-14f0-411d-8141-c5504cec4963" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Usage>Global</Usage>
        <DataType>INT</DataType>
        <Address />
        <InitValue>INT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <Access>I</Access>
        <DataType>Signed16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a6b0e559-4f4e-4b27-ad3c-99f60c93d75c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="25325d76-c9f4-4dd6-a8ef-7f6bbe7a4e35" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5b909b09-69b6-4d68-85f7-45be5daef56f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="353b18db-1ded-4de5-8b06-f217964f0a5e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="26e43d29-d443-41e3-8a14-9c8dd59fd1c2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="79a3cdba-50c4-4803-89b3-423a15391d3f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="33cdbc6d-f0f8-4bba-86e6-9eb4306f0fef">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="35abfcf7-ceb6-4f11-8fff-4da7370826ba" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d001d37c-643f-4393-a1e6-1f6ee65a540d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f653ef11-1578-4f9d-b9f7-2fc4b9368a84" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b784cf49-0df8-4c7b-a46e-506fc4dd2843">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b897005f-bd04-45f2-af7a-30e2bfb6706c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4cd7945a-2fd7-4ba8-bb35-865f190cf428">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6d507cc5-3755-4c24-ba3a-543f99f82b5f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="66296b70-a73f-495d-bd1e-437b3eb0631f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5565b2ef-a41c-4c6b-8ce8-5ede565fd10e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fd60e43d-f159-47a9-8dbc-1a14e6db54ef">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c7550777-3485-4f80-90ac-0b89e9e32949" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f94c1da7-643d-4b99-a0b6-5b0dd94c2835">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="deab3b82-f33a-4669-858a-e15619b47fc6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="867c8b7d-338d-4880-a79c-9b057f4d9ddf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="09d80498-b15e-430d-b557-946365d1aa3f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1b4737fc-4803-4210-ad74-f13ab37586b5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="bc21bb1d-1732-4a7c-9a6d-908453082362" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="db6bd392-9272-4ad2-9d52-e29eee4487ce">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="98121d98-f2ea-48c0-8c28-b16fa4ee9b40" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0bd637e1-6b20-41ac-a540-cb5d7901b23f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0b96398b-b743-42dc-8baf-ae198c4e46f8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9ce3dac9-3e2a-4ab4-a01f-e333ff950b5e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9a033908-059c-4e6c-a74d-6c8cacb1cd9c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8eb81a16-aff9-4c8c-83fd-697b6cafbbf7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5ab695dc-3e23-4955-ac9c-034c14f522f8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3ff37ccf-63e8-462b-8d41-8657bb7d255d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d06764cb-e936-4523-9d4d-fe067c0a01a1" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="89ce3227-ffcd-4080-b394-7077fe768295">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="51fc56f8-3a4b-4b76-9c98-fd0eef48007d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ecd7dc82-c2b3-4880-bb4f-43cbe2edb3c0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a085ad0e-f360-4e8f-bfb4-3310da4d6830" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="154d544a-b43b-4792-a6fc-0c97844d1db8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="92a49d27-e60f-458e-adb3-9928d5ffdf38" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="76f6efb5-1891-4419-bf4d-af6de0ff0c5e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="11be59fb-18d1-43db-8131-f7cae1374632" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c0cd6f24-e2e0-4d78-afeb-6cefa8f15f80">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8d039083-8224-4dc1-b92b-e1ba7b7bcf71" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1abc4c73-ed5a-4901-8fea-e14fd15e1bff">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="65437c6b-cbc4-41ec-aff8-063d0f792d76" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="df79e63a-8c0c-46ad-bd8d-6561732cdaae">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="366156b1-980e-4742-bf26-0766191bea89" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5288d288-2ca6-4a66-888c-683019478743">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="73dc532d-0c76-4e57-a35a-55e41717c539" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d509af61-4228-4b8d-b293-d10771388098">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fdaa1945-79c0-415e-ba8e-11687b349b7e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f8a2a584-5a11-4de6-8d32-fb9970891caf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="acfb9ef6-3118-4165-95b3-6f24ca8f6f45" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3431fe3e-5a90-4e6d-9a2d-42a3bb6ce448">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="eb754a75-ed55-4262-b93e-6037b2f968f0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bab2de68-d283-4ca5-82a5-92f845d767e8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d435c6a7-e457-430e-b98a-de6d6975d477" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="268bd7bb-9b9d-40c9-86ac-ed2f167fdd18">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e140a589-dcd8-4496-a48b-9af3d47bc2b4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7df70b10-196f-44d3-a047-5edcf494fb4c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7cf86e0d-4140-46a3-924d-b5724040d40a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>ESM_DATA</Name>
        <Usage>Global</Usage>
        <DataType>ESM_DAT</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_1">
        <Label>ESM_DATA</Label>
        <Access>I</Access>
        <DataType>ESM_DAT</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ab9448ba-9ca2-4d5c-b91c-d8e6fdc7017e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f0451de9-60b3-4e48-9ed8-85e9cf3f36f6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>RTC</Name>
        <Usage>Global</Usage>
        <DataType>RTC_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_1">
        <Label>RTC</Label>
        <Access>I</Access>
        <DataType>RTC_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="63cc1b71-f95e-4a94-897d-49ce28edb035">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8fe93b48-c1fb-4b5a-91b6-3f8ba950b0b0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>DEVICE_STATE</Name>
        <Usage>Global</Usage>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_1">
        <Label>DEVICE_STATE</Label>
        <Access>I</Access>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4eca2ccb-4a2a-4853-adf9-b0d8d9d4ed26">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="45a7d125-b34a-405f-972e-8e5a4bb2d907" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>USER_PARTITION</Name>
        <Usage>Global</Usage>
        <DataType>PARTITION_INFO</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pddi4]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_1">
        <Label>USER_PARTITION</Label>
        <Access>I</Access>
        <DataType>PARTITION_INFO</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="56bbda2a-f94e-4bdf-8a0f-d92495b80249">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a0805290-998b-4090-a01c-1216661d7a17" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_SYSTEM_BF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_SYSTEM_BF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0d043f11-e0d0-4b62-a9c1-d563f641aca5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="16deab6a-e33b-4c7b-ab9d-28a937d5185a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_SYSTEM_SF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_SYSTEM_SF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="44a6bf8e-ba80-45b1-b94a-862cc36d7a53">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="09101d34-7fba-451a-b0bf-7552605b6621" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ac99f125-6d75-4de3-9115-bc06f7106527">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6fba4df3-697b-4e3b-924b-14476234cb74" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d35dd42b-8809-4ab1-b062-2fda9e83417d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f5863e43-d5f5-4ef2-9f5b-da653a2a0e1d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_CONFIG_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_CONFIG_STATUS</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3c47b627-0ff8-4f0c-b21e-8fa693655688">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="00f28c99-b418-4b86-86b1-02113e44811b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7043178f-ae03-44f8-8484-1dd884d0d5f4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d85c0211-b61e-411d-be83-eaec4ae59b05" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="367f63a0-c347-414a-9f61-e0153de667ba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6615773e-4710-4a3d-8046-10a76d003dc4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="33c3b5d5-654c-4ace-a158-2ecbd9c9daf5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e3058389-8343-46c1-a01d-d9f338bf3fa4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d6c5c822-31ff-44b3-87dd-e4e47d9fe959">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b4b5e25a-c5fd-4026-ba35-d6c2634eed6b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>PNIO_FORCE_PRIMARY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=pncpd10]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_4">
        <Label>PNIO_FORCE_PRIMARY</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="56803d70-e5f9-448c-807f-6b9398fa3de4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7d6249ce-12b2-4158-a276-dca98656b81b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30000</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>IP_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3220eb68-9f55-4f15-97a1-c370e3227092">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="17a597eb-965b-472f-a2bc-1a032e79ee37" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30100</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>TLS_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="90a86b38-3419-484a-ab12-7cd048702521">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="77dacfc2-c96e-42c0-a2cc-745e1daafc78" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>HMI_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>HMI_STATUS_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>HMI_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_3">
        <Label>HMI_STATUS</Label>
        <Access>I</Access>
        <DataType>HMI_STATUS_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>HMI Webserver / HMI_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="20ca1326-91f4-4872-9e33-e0a692960270">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="00c31b46-03d4-4606-965b-1843a3af439f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>HMI_CONTROL</Name>
        <Usage>Global</Usage>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_3">
        <Label>HMI_CONTROL</Label>
        <Access>Q</Access>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>HMI Webserver / HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f3659ed4-9655-443c-a7f5-eb76bc8248e8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6e706e78-3c17-46c4-a45b-a19367f98744" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_INPUTS</Label>
        <Access>I</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="38351591-0137-420c-a952-8d6845060448">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8d3d0e45-9f2e-45d9-853c-2a26557e8434" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a16fbd07-4cb4-444b-beb1-3506ef5cfa54">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="48057500-eaf2-4780-b13c-6813c32d8515" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4dcd0c9f-667e-4e62-89ff-1d0dbab2a15b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a22efb13-63cc-4cab-9ff2-6eea658f8cb5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_PEER_IDLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_PEER_IDLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b43e6c8e-ad31-4766-b94a-6c7423aa15dd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="510df444-0e88-493a-8a66-108fbc482e34" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_PEER_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_PEER_RUN</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="65d714d2-a977-4a55-aa80-744060054ff1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c3aa4faa-f065-464c-b789-02584aad110b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="80a5cea8-e8d6-4df1-8d8a-f1308f70af16">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f0eb9959-f0b5-450f-be04-b3a3c49d61d5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec">
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_7">
        <Label>EIPD_INPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="52b91a73-fae4-48d1-a632-63bccb20eca0">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="StopCounting" SourceId="53d3fb3b-e577-4a63-80f7-338a25ee3ff4">
        <Name>StopCounting</Name>
        <DataType>boolean</DataType>
        <PortDataTypeDomain>PlcNext</PortDataTypeDomain>
        <PortDataType>boolean</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>CounterComponent1</ComponentInstance>
        <DisplayName>CounterComponent1 : StopCounting</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="abb618c7-18aa-4333-996a-0c6e580761f7">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="StopCounting" SourceId="53d3fb3b-e577-4a63-80f7-338a25ee3ff4">
        <Name>StopCounting</Name>
        <DataType>boolean</DataType>
        <PortDataTypeDomain>PlcNext</PortDataTypeDomain>
        <PortDataType>boolean</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>CounterComponent1</ComponentInstance>
        <DisplayName>CounterComponent1 : StopCounting</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1255427e-05b6-42c6-a64b-763576e648b8">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="Down_Counter" SourceId="00beb470-0c58-4ef9-8a1f-64fe45843ee1">
        <Name>Down_Counter</Name>
        <DataType>uint8</DataType>
        <PortDataTypeDomain>PlcNext</PortDataTypeDomain>
        <PortDataType>uint8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>CounterComponent1</ComponentInstance>
        <ProgramInstance>DownCounterProgram1</ProgramInstance>
        <Program>CounterComponent1 / DownCounterProgram1</Program>
        <DisplayName>CounterComponent1 / DownCounterProgram1 : Down_Counter</DisplayName>
      </Role>
      <Role TypeName="InPort" ObjectId="c028ad22-c93f-4df6-88b1-c6031ced52b3" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_2">
        <Name>DOWN</Name>
        <DataType>INT</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>INT</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>NewProgram1</ProgramInstance>
        <Program>Arp.Plc.Eclr / NewProgram1</Program>
        <DisplayName>Arp.Plc.Eclr / NewProgram1 : DOWN</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="ac727e6f-05b6-4181-844d-90fb3cfea594">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="UP_Counter" SourceId="e0dbfa16-776f-48e8-a078-efc561c1c353">
        <Name>UP_Counter</Name>
        <DataType>uint8</DataType>
        <PortDataTypeDomain>PlcNext</PortDataTypeDomain>
        <PortDataType>uint8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>CounterComponent1</ComponentInstance>
        <ProgramInstance>UpCounterProgram1</ProgramInstance>
        <Program>CounterComponent1 / UpCounterProgram1</Program>
        <DisplayName>CounterComponent1 / UpCounterProgram1 : UP_Counter</DisplayName>
      </Role>
      <Role TypeName="InPort" ObjectId="de355d38-f992-42bb-bb99-a17e55bab95a" SourceId="6aff7cb6-d8e0-48c1-a326-d8cad274e635.L7_2">
        <Name>UP</Name>
        <DataType>INT</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>INT</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>NewProgram1</ProgramInstance>
        <Program>Arp.Plc.Eclr / NewProgram1</Program>
        <DisplayName>Arp.Plc.Eclr / NewProgram1 : UP</DisplayName>
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False" />
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/c0b77aed-a4c9-465c-8c13-2484eb65ebec" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>b91054d5-6d7e-4f44-bb48-5d7d3cf4a598</RoleDatumUuid>
        <RoleDatumUuid>cc97169a-51ac-4974-9133-faf5af9aaa63</RoleDatumUuid>
        <RoleDatumUuid>dcfc2182-9a92-45e8-b3bd-7c0d73a60c2d</RoleDatumUuid>
        <RoleDatumUuid>18f1b8ce-b876-4a42-8d8a-ede41bc0ae0c</RoleDatumUuid>
        <RoleDatumUuid>45ca5bb5-e2e9-44f9-a0e2-2af4f25d8609</RoleDatumUuid>
        <RoleDatumUuid>020bf624-745e-42af-841d-b9bd786c616f</RoleDatumUuid>
        <RoleDatumUuid>8d532e75-8dac-46e4-9a67-d4070d96b144</RoleDatumUuid>
        <RoleDatumUuid>9a9be554-9506-48f8-9200-8019b53e7804</RoleDatumUuid>
        <RoleDatumUuid>a6b0e559-4f4e-4b27-ad3c-99f60c93d75c</RoleDatumUuid>
        <RoleDatumUuid>5b909b09-69b6-4d68-85f7-45be5daef56f</RoleDatumUuid>
        <RoleDatumUuid>26e43d29-d443-41e3-8a14-9c8dd59fd1c2</RoleDatumUuid>
        <RoleDatumUuid>33cdbc6d-f0f8-4bba-86e6-9eb4306f0fef</RoleDatumUuid>
        <RoleDatumUuid>d001d37c-643f-4393-a1e6-1f6ee65a540d</RoleDatumUuid>
        <RoleDatumUuid>b784cf49-0df8-4c7b-a46e-506fc4dd2843</RoleDatumUuid>
        <RoleDatumUuid>4cd7945a-2fd7-4ba8-bb35-865f190cf428</RoleDatumUuid>
        <RoleDatumUuid>66296b70-a73f-495d-bd1e-437b3eb0631f</RoleDatumUuid>
        <RoleDatumUuid>fd60e43d-f159-47a9-8dbc-1a14e6db54ef</RoleDatumUuid>
        <RoleDatumUuid>f94c1da7-643d-4b99-a0b6-5b0dd94c2835</RoleDatumUuid>
        <RoleDatumUuid>867c8b7d-338d-4880-a79c-9b057f4d9ddf</RoleDatumUuid>
        <RoleDatumUuid>1b4737fc-4803-4210-ad74-f13ab37586b5</RoleDatumUuid>
        <RoleDatumUuid>db6bd392-9272-4ad2-9d52-e29eee4487ce</RoleDatumUuid>
        <RoleDatumUuid>0bd637e1-6b20-41ac-a540-cb5d7901b23f</RoleDatumUuid>
        <RoleDatumUuid>9ce3dac9-3e2a-4ab4-a01f-e333ff950b5e</RoleDatumUuid>
        <RoleDatumUuid>8eb81a16-aff9-4c8c-83fd-697b6cafbbf7</RoleDatumUuid>
        <RoleDatumUuid>3ff37ccf-63e8-462b-8d41-8657bb7d255d</RoleDatumUuid>
        <RoleDatumUuid>89ce3227-ffcd-4080-b394-7077fe768295</RoleDatumUuid>
        <RoleDatumUuid>ecd7dc82-c2b3-4880-bb4f-43cbe2edb3c0</RoleDatumUuid>
        <RoleDatumUuid>154d544a-b43b-4792-a6fc-0c97844d1db8</RoleDatumUuid>
        <RoleDatumUuid>76f6efb5-1891-4419-bf4d-af6de0ff0c5e</RoleDatumUuid>
        <RoleDatumUuid>c0cd6f24-e2e0-4d78-afeb-6cefa8f15f80</RoleDatumUuid>
        <RoleDatumUuid>1abc4c73-ed5a-4901-8fea-e14fd15e1bff</RoleDatumUuid>
        <RoleDatumUuid>df79e63a-8c0c-46ad-bd8d-6561732cdaae</RoleDatumUuid>
        <RoleDatumUuid>5288d288-2ca6-4a66-888c-683019478743</RoleDatumUuid>
        <RoleDatumUuid>d509af61-4228-4b8d-b293-d10771388098</RoleDatumUuid>
        <RoleDatumUuid>f8a2a584-5a11-4de6-8d32-fb9970891caf</RoleDatumUuid>
        <RoleDatumUuid>3431fe3e-5a90-4e6d-9a2d-42a3bb6ce448</RoleDatumUuid>
        <RoleDatumUuid>bab2de68-d283-4ca5-82a5-92f845d767e8</RoleDatumUuid>
        <RoleDatumUuid>268bd7bb-9b9d-40c9-86ac-ed2f167fdd18</RoleDatumUuid>
        <RoleDatumUuid>7df70b10-196f-44d3-a047-5edcf494fb4c</RoleDatumUuid>
        <RoleDatumUuid>ab9448ba-9ca2-4d5c-b91c-d8e6fdc7017e</RoleDatumUuid>
        <RoleDatumUuid>63cc1b71-f95e-4a94-897d-49ce28edb035</RoleDatumUuid>
        <RoleDatumUuid>4eca2ccb-4a2a-4853-adf9-b0d8d9d4ed26</RoleDatumUuid>
        <RoleDatumUuid>56bbda2a-f94e-4bdf-8a0f-d92495b80249</RoleDatumUuid>
        <RoleDatumUuid>0d043f11-e0d0-4b62-a9c1-d563f641aca5</RoleDatumUuid>
        <RoleDatumUuid>44a6bf8e-ba80-45b1-b94a-862cc36d7a53</RoleDatumUuid>
        <RoleDatumUuid>ac99f125-6d75-4de3-9115-bc06f7106527</RoleDatumUuid>
        <RoleDatumUuid>d35dd42b-8809-4ab1-b062-2fda9e83417d</RoleDatumUuid>
        <RoleDatumUuid>3c47b627-0ff8-4f0c-b21e-8fa693655688</RoleDatumUuid>
        <RoleDatumUuid>7043178f-ae03-44f8-8484-1dd884d0d5f4</RoleDatumUuid>
        <RoleDatumUuid>367f63a0-c347-414a-9f61-e0153de667ba</RoleDatumUuid>
        <RoleDatumUuid>33c3b5d5-654c-4ace-a158-2ecbd9c9daf5</RoleDatumUuid>
        <RoleDatumUuid>d6c5c822-31ff-44b3-87dd-e4e47d9fe959</RoleDatumUuid>
        <RoleDatumUuid>56803d70-e5f9-448c-807f-6b9398fa3de4</RoleDatumUuid>
        <RoleDatumUuid>3220eb68-9f55-4f15-97a1-c370e3227092</RoleDatumUuid>
        <RoleDatumUuid>90a86b38-3419-484a-ab12-7cd048702521</RoleDatumUuid>
        <RoleDatumUuid>20ca1326-91f4-4872-9e33-e0a692960270</RoleDatumUuid>
        <RoleDatumUuid>f3659ed4-9655-443c-a7f5-eb76bc8248e8</RoleDatumUuid>
        <RoleDatumUuid>38351591-0137-420c-a952-8d6845060448</RoleDatumUuid>
        <RoleDatumUuid>a16fbd07-4cb4-444b-beb1-3506ef5cfa54</RoleDatumUuid>
        <RoleDatumUuid>4dcd0c9f-667e-4e62-89ff-1d0dbab2a15b</RoleDatumUuid>
        <RoleDatumUuid>b43e6c8e-ad31-4766-b94a-6c7423aa15dd</RoleDatumUuid>
        <RoleDatumUuid>65d714d2-a977-4a55-aa80-744060054ff1</RoleDatumUuid>
        <RoleDatumUuid>80a5cea8-e8d6-4df1-8d8a-f1308f70af16</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>