name: Build all examples
run-name: ${{ github.actor }} is building all examples
on: [workflow_dispatch]
jobs:
  build-all-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2023.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build the DataAccess example
        # Globalisation invariant mode must be set to avoid errors in EngineeringLibraryBuilder.
        # See: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization
        run: |
          plcncli --version
          plcncli new acfproject --output Build/DataAccess
          cp Examples/DataAccess/src/* Build/DataAccess/src/*
          plcncli set target --path Build/DataAccess --name AXCF2152 --version 2023.0 --add
          plcncli generate all --path Build/DataAccess
          plcncli build --path Build/DataAccess --buildtype Release
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          plcncli deploy --path Build/DataAccess
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataAccess
          path: Build/DataAccess/bin
