name: Build all examples
run-name: ${{ github.actor }} is building all examples
on: [workflow_dispatch]
jobs:
  build-all-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2023.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      # DYNAMIC PORTS EXAMPLE
      # - includes a work-around for bug https://github.com/PLCnext/PLCnext_CLI_Templates/issues/5
      - name: Build the DynamicPorts example
        # Globalisation invariant mode must be set to avoid errors in EngineeringLibraryBuilder.
        # See: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization
        run: |
          plcncli --version
          mkdir -p Build
          cd Build
          plcncli new project --output DynamicPorts
          cd ..
          cp Examples/DynamicPorts/src/* Build/DynamicPorts/src
          plcncli set target --path Build/DynamicPorts --name AXCF2152 --version 2023.0 --add
          plcncli generate all --path Build/DynamicPorts
          plcncli build --path Build/DynamicPorts --buildtype Release
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          plcncli deploy --path Build/DynamicPorts
      - name: Archive DynamicPorts build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DynamicPorts
          path: Build/DynamicPorts/bin
      # COMPONENT PORTS EXAMPLE
      - name: Build the ComponentPorts example
        run: |
          plcncli --version
          mkdir -p Build
          cd Build
          plcncli new project --output ComponentPorts
          cd ..
          rm Build/ComponentPorts/src/*
          cp Examples/ComponentPorts/src/* Build/ComponentPorts/src
          plcncli set target --path Build/ComponentPorts --name AXCF2152 --version 2023.0 --add
          plcncli generate all --path Build/ComponentPorts
          plcncli build --path Build/ComponentPorts --buildtype Release
          plcncli deploy --path Build/ComponentPorts
      - name: Archive ComponentPorts build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ComponentPorts
          path: Build/ComponentPorts/bin
      # DATA ACCESS EXAMPLE
      - name: Build the DataAccess example
        run: |
          plcncli new acfproject --output Build/DataAccess
          cp Examples/DataAccess/src/* Build/DataAccess/src
          plcncli set target --path Build/DataAccess --name AXCF2152 --version 2023.0 --add
          plcncli generate all --path Build/DataAccess
          plcncli build --path Build/DataAccess --buildtype Release
          plcncli deploy --path Build/DataAccess
      - name: Archive DataAccess build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataAccess
          path: Build/DataAccess/bin
