name: Build all examples
run-name: ${{ github.actor }} is building all examples
on: [workflow_dispatch]
jobs:
  build-all-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2022.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build the DataAccess example
        run: |
          plcncli --version
          plcncli new acfproject --component DummyC --output Examples/DataAccess
          rm Examples/DataAccess/src/Dummy*
          plcncli set target --path Examples/DataAccess --name AXCF2152 --version 2022.6 --add
          plcncli generate all --path Examples/DataAccess
          plcncli build --path Examples/DataAccess --buildtype Release
          plcncli deploy --path Examples/DataAccess
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataAccess
          path: Examples/DataAccess/bin
